### ISSUE TITLE
由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败

### ISSUE THREAD

**Issue by doulemint** [soaringsoul/easypoi#2]
Traceback (most recent call last):
  File "C:\Users\stone\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\stone\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\stone\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\stone\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\stone\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\stone\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Users\stone\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Users\stone\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 181, in connect
    conn = self._new_conn()
  File "C:\Users\stone\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000221015CDDD8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\stone\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\stone\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\stone\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='restapi.amap.com', port=80): Max retries exceeded with url: /v3/config/district?keywords=%E4%B8%AD%E7%89%9F%E5%8E%BF&key=19b6a10f26bfc2ef5ff7014d126350f4&subdistrict=3&extensions=all&output=JSON (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000221015CDDD8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\stone\AppData\Local\Programs\Python\Python36\lib\site-packages\scrapy\core\engine.py", line 127, in _next_request
    request = next(slot.start_requests)
  File "D:\AndroidProject\周边商家\周边商家\python\BaiduMapPoiSpider\BaiduMapWebApiSpier\spiders\web_api_spider.py", line 43, in start_requests
    poly = get_region_polyline(region_name)
  File "D:\AndroidProject\周边商家\周边商家\python\BaiduMapPoiSpider\BaiduMapWebApiSpier\util\geo\amap_get_geopolylines.py", line 20, in get_region_polyline
    response = requests.get(url, params=_parms)
  File "C:\Users\stone\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\stone\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\stone\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\stone\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\stone\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='restapi.amap.com', port=80): Max retries exceeded with url: /v3/config/district?keywords=%E4%B8%AD%E7%89%9F%E5%8E%BF&key=19b6a10f26bfc2ef5ff7014d126350f4&subdistrict=3&extensions=all&output=JSON (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000221015CDDD8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
2019-07-09 14:28:12 [scrapy.core.engine] INFO: Closing spider (finished)
2019-07-09 14:28:12 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'finish_reason': 'finished',
 'finish_time': datetime.datetime(2019, 7, 9, 6, 28, 12, 34469),
 'log_count/ERROR': 1,
 'log_count/INFO': 7,
 'start_time': datetime.datetime(2019, 7, 9, 6, 27, 50, 979586)}
2019-07-09 14:28:12 [scrapy.core.engine] INFO: Spider closed (finished)

触发了百度并发预警之后，换了AK就出现connection fail的错误。 这不会是让我氪金了吧.还是其他错误呀？

**Comment by doulemint** [comment]
ip变了，所以AK无效。。我关了
