### ISSUE TITLE
KeyError: 'districts'

### ISSUE THREAD

**Issue by doulemint** [soaringsoul/easypoi#3]
2019-07-09 16:45:16 [scrapy.core.engine] INFO: Spider closed (finished)
2019-07-09 16:48:18 [scrapy.utils.log] INFO: Scrapy 1.5.1 started (bot: BaiduMapWebApiSpier)
2019-07-09 16:48:18 [scrapy.utils.log] INFO: Versions: lxml 4.2.5.0, libxml2 2.9.5, cssselect 1.0.3, parsel 1.5.1, w3lib 1.20.0, Twisted 19.2.1, Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)], pyOpenSSL 19.0.0 (OpenSSL 1.1.1c  28 May 2019), cryptography 2.7, Platform Windows-10-10.0.17134-SP0
2019-07-09 16:48:18 [scrapy.crawler] INFO: Overridden settings: {'BOT_NAME': 'BaiduMapWebApiSpier', 'LOG_FILE': 'log.txt', 'LOG_LEVEL': 'INFO', 'NEWSPIDER_MODULE': 'BaiduMapWebApiSpier.spiders', 'SPIDER_MODULES': ['BaiduMapWebApiSpier.spiders']}
2019-07-09 16:48:19 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2019-07-09 16:48:19 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2019-07-09 16:48:19 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2019-07-09 16:48:19 [scrapy.middleware] INFO: Enabled item pipelines:
['BaiduMapWebApiSpier.pipelines.BaidumapwebapispierPipeline']
2019-07-09 16:48:19 [scrapy.core.engine] INFO: Spider opened
2019-07-09 16:48:19 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2019-07-09 16:48:19 [scrapy.core.engine] ERROR: Error while obtaining start requests
Traceback (most recent call last):
  File "C:\Users\stone\AppData\Local\Programs\Python\Python36\lib\site-packages\scrapy\core\engine.py", line 127, in _next_request
    request = next(slot.start_requests)
  File "D:\AndroidProject\周边商家\周边商家\python\BaiduMapPoiSpider\BaiduMapWebApiSpier\spiders\web_api_spider.py", line 43, in start_requests
    poly = get_region_polyline(region_name)
  File "D:\AndroidProject\周边商家\周边商家\python\BaiduMapPoiSpider\BaiduMapWebApiSpier\util\geo\amap_get_geopolylines.py", line 23, in get_region_polyline
    polyline = data['districts'][0]['polyline']
KeyError: 'districts'
2019-07-09 16:48:19 [scrapy.core.engine] INFO: Closing spider (finished)
2019-07-09 16:48:19 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'finish_reason': 'finished',
 'finish_time': datetime.datetime(2019, 7, 9, 8, 48, 19, 883932),
 'log_count/ERROR': 1,
 'log_count/INFO': 7,
 'start_time': datetime.datetime(2019, 7, 9, 8, 48, 19, 785197)}
2019-07-09 16:48:19 [scrapy.core.engine] INFO: Spider closed (finished)

只有市级的成功了，区县的不知道为啥错误。中文，编码都试了不知道是不是region_name_list内的错误

**Comment by soaringsoul** [comment]
你好，测试了下区县级的，可以正常运行，请把你出错的区县名发一下，我这边调试一下。
